environment_config:
  env_type: "hopper" 
  max_ep_len: 1000
  returns_scale: 1000

dataset_config:
  is_local: [true]
  online_policy_names: ["d4rl"]
  dataset_types: ["medium"]
  dataset_versions: [""]

model_config:
  agent_type: "dt"
  context_size: [20]
  lambda1: [1.0]
  lambda2: [1.0]

training_config:
  train_steps: 4
  warmup_steps: [3]
  train_batch_size: [64]
  learning_rate: [-4]
  weight_decay: [-4]
  max_grad_norm: [0.25] 
  seeds: [33, 66, 99]

admin_config:
  wandb_project: "d4rl" 
  hf_project: "d4rl"
  run_type: "core"
