environment_config:
  env_type: "hopper"  # halfcheetah, hopper, walker2d
  max_ep_len: 1000  # limit episode length for offline dataset
  max_ep_return: 12000  # max "possible" returns per episode of size max_ep_len
  returns_scale: 1000  # scale returns, 1000 to match original DT implementation

dataset_config:
  is_local: [true]  # true, false, whether it is stored locally or up on HF - a list
  online_policy_names: ["arrl"]  # d4rl, rarl, arrl_nrdmp, arrl_prmdp, dataset_combo, etc. - a list
  dataset_types: ["train"]  # train, test, expert - a list
  dataset_versions: ["v1"]  # fill only if there is any type of versioning to the dataset being considered, otherwise insert empty strings - a list

model_config:
  agent_type: "ardt-full"  # dt, ardt-simplest, ardt-vanilla, ardt-full
  context_size: [20]  # these are for different parameter combinations to try!! | original: 20 (depends a bit on env)
  lambda1: [1.0]  # these are for different parameter combinations to try!!
  lambda2: [250]  # these are for different parameter combinations to try!!

training_config:
  train_steps: 2  # 6 => 10**6
  train_batch_size: 64  # 32/64
  learning_rate: [-4]  # these are for different parameter combinations to try!! e.g. -4 => 10**-4 | original: -4
  weight_decay: [-4]  # these are for different parameter combinations to try!! e.g. -4 => 10**-4 | original: -4
  max_grad_norm: [0.25]  # these are for different parameter combinations to try!! | original: 0.25
  warmup_steps: [1]  # these are for different parameter combinations to try!! again 4 => 10**4 | original: 10**5

evaluation_config:
  is_eval: false  # whether to run evaluation
  eval_type: ""  # no_adv, env_adv, agent_adv
  eval_target_return: 12000  # note this should depend on environment!! 12k/6k for halfcheetah for example
  eval_iters: 20  # just enough to get some CLT going
  # only if using an explicit adversary!! i.e. eval_type = "agent_adv"
  adv_model_names: []  # names from models stored on the repo
  adv_model_types: []  # dt, ardt-simplest, ardt-vanilla, ardt-full

admin_config:
  wandb_project: "afonsosamarques"  # "afonsosamarques", "ARDT-Project", "ARDT-Internal"
  hf_project: "afonsosamarques"  # "afonsosamarques", "ARDT-Project", "ARDT-Internal"
  run_type: "test"  # "core", "pipeline", or "test"
  is_verbose: false  # whether to print anything at all
  print_tracebacks: false  # whether to print tracebacks of errors
